version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@db:5432/npi_calculator"
      - DB_HOST=db
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=npi_calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
